config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    sessions: "admin/sessions"
  }
  devise_for(
    :users,
    controllers: {
      sessions: "user/sessions",
      passwords: "user/passwords",
      registrations: "user/registrations",
      omniauth_callbacks: "user/omniauth_callbacks"
    }
  )
  get 'products/show'

  get 'index/index'
  resource :cart, only:[:show, :destroy] do
    member do
      post :add, path: 'add/:id/(:quantity)'
      post :update_quantity, path: 'update/:id'
      delete :remove, path: 'remove/:id'
      get "checkout"
    end
  end
  resources :orders, only:[:index, :new, :create, :show]

  resources :cities, only:[] do
    scope module: :cities do
      member do
        resources :areas, only:[:index]
      end
    end
  end

  root "index#index"

  resources :products
  resources :articles
  resources :contracts, only:[:new, :create]


  namespace :admin do
    root 'products#index'
    devise_scope :admin do
      authenticated :admin do
        root 'products#index', as: :authenticated_root
      end
    end
    resources :products do
        scope module: :products do
          resources :images, only: [:index, :create, :destroy]
          resources :specs do
            member do
              get :switch_seq, path: 'switch/:target_id'
            end
          end
        end
    end
    resources :orders do
      scope module: :orders do
        resources :items
      end
    end

    resources :users
    resources :contracts
  end

  get 'about/index'
  get 'note/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  has_many :specs
  scope :publish, -> { where(is_finish: true).where(is_public: true) }

  validates_presence_of :name, :price, :description, :description_2

  before_update do
    self.is_finish ||= true
  end

end

app/models/product/image.rb
class Product::Image < ApplicationRecord
  belongs_to :product
  mount_uploader :file, ProductImageUploader
end

app/models/product/spec.rb
class Product::Spec < ApplicationRecord
  belongs_to :product

  validates_presence_of :title, :price

  mount_uploader :image, ProductSpecImageUploader

  before_create do
    self.seq = self.class.where(product_id: self.product_id).size + 1
  end

  def full_title
    "#{product.title} - #{title}"
  end

end

app/controllers/admin/products/images_controller.rb
class Admin::Products::ImagesController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token, :only => [:index, :create, :destroy]

  def index
    images = ::Product.find(params[:product_id]).images
    images = images.map do |image|
      {
        id: image.id,
        file_url: image.file.url ,
        file_name: image.file.file.filename
      }
    end

    render json: images.to_json, status: :ok

  end

  def create
    image = Product::Image.new(
      product: Product.find(params[:product_id]),
      file: params[:file]
    )

    if image.save

      response_image = {}
      response_image[:id] = image.id
      response_image[:file_url] = image.file.url
      response_image[:file_name] = image.file.file.filename

      render json: {
        image: response_image.to_json,
        filelink: image.file.url
      }, status: :ok
    else
      render json: { errors: service.errors.full_messages.last }, status: :unprocessable_entity
    end
  end

  def destroy
    product = Product.find params[:product_id]
    product.images.delete(Product::Image.find(params[:id]))
    render json: {}, status: :ok
  end
end

app/controllers/admin/products/specs_controller.rb
class Admin::Products::SpecsController < ResourcesController

  before_action :authenticate_admin!
  layout "admin"

  before_action only: [:new, :edit, :update, :create] do
    @product = ::Product.find params[:product_id]
  end

  def current_collection
    ::Product::Spec.all.order(:product_id, :seq)
  end

  def permitted_attributes
    [
      :title, :price, :product_id, :image, :seq
    ]
  end

  def switch_seq
    specs  = ::Product.find(params[:product_id]).specs
    source = specs.find(params[:id])
    target = specs.find(params[:target_id])

    source.seq = target.seq
    target.seq = source.seq_was
    source.save! and target.save!

    redirect_to edit_admin_product_path(params[:product_id])
  end

  def action_after_create
    edit_admin_product_spec_path(@product.id, current_collection.last.id)
  end

  def param_key
    "product_spec"
  end

  def model_class_name
    "Product::Spec"
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ResourcesController

  before_action :authenticate_admin!

  layout "admin"

  def new
    Product.new.save(validate: false)
    redirect_to edit_admin_product_path(Product.last.id)
  end

  def current_collection
    ::Product.where(is_finish: true)
  end

  def permitted_attributes
    [
      :name, :price, :description,
      :description_2, :is_public,
    ]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find params[:id]
  end
end

app/helpers/admin/product/images_helper.rb
module Admin::Product::ImagesHelper
end

app/helpers/admin/products/specs_helper.rb
module Admin::Products::SpecsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/specs/_form.html.erb
<%= simple_form_for current_object, url: url, html: { class: 'form-horizontal' } do |f| %>
<%= render partial: 'shared/save', locals: { f: f, cancel_path: edit_admin_product_path(@product) } %>
<div class="form-body">
  <%= f.input :product_id, as: :hidden, input_html: {value: @product.id, class: 'form-control', class: 'input-large'} %>
  <%= f.input :title, input_html: {class: 'form-control', class: 'input-large'} %>
  <%= f.input :price, input_html: {class: 'form-control', class: 'input-large'} %>
  <%= f.input :image, as: :image %>
</div>

<%= render partial: 'shared/save', locals: { f: f, cancel_path: edit_admin_product_path(@product) } %>
<% end %>

app/views/admin/products/specs/edit.html.erb
<div class="page-bar">
  <%= breadcrumb(link_to('商品', admin_products_path), link_to(@product.name, edit_admin_product_path(@product)), '新增商品規格') %>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h2 class="page-header">
        <%= @product.name %>
      </h2>
      <div class="portlet box blue">
        <div class="portlet-title">
          <div class="caption">
            修改規格
          </div>
        </div>
        <div class="portlet-body form">
          <%= render partial: 'form', locals: { url: admin_product_spec_path(@product.id, current_object) } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/specs/new.html.erb
<div class="page-bar">
  <%= breadcrumb(link_to('商品', admin_products_path), link_to(@product.name, edit_admin_product_path(@product)), '新增商品規格') %>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h2 class="page-header">
        <%= @product.name %>
      </h2>
      <div class="portlet box blue">
        <div class="portlet-title">
          <div class="caption">
            新增規格
          </div>
        </div>
        <div class="portlet-body form">
          <%= render partial: 'form', locals: { url: admin_product_specs_path(@product.id) } %>
        </div>
      </div>
    </div>
  </div>
</div>