config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    sessions: "admin/sessions"
  }
  devise_for(
    :users,
    controllers: {
      sessions: "user/sessions",
      passwords: "user/passwords",
      registrations: "user/registrations",
      omniauth_callbacks: "user/omniauth_callbacks"
    }
  )
  get 'products/show'

  get 'index/index'
  resource :cart, only:[:show, :destroy] do
    member do
      post :add, path: 'add/:id/(:quantity)'
      post :update_quantity, path: 'update/:id'
      delete :remove, path: 'remove/:id'
      get "checkout"
    end
  end
  resources :orders, only:[:index, :new, :create, :show]

  resources :cities, only:[] do
    scope module: :cities do
      member do
        resources :areas, only:[:index]
      end
    end
  end

  root "index#index"

  resources :products
  resources :articles
  resources :contracts, only:[:new, :create]


  namespace :admin do
    root 'products#index'
    devise_scope :admin do
      authenticated :admin do
        root 'products#index', as: :authenticated_root
      end
    end
    resources :products do
        scope module: :products do
          resources :images, only: [:index, :create, :destroy]
          resources :specs do
            member do
              get :switch_seq, path: 'switch/:target_id'
            end
          end
        end
    end
    resources :orders do
      scope module: :orders do
        resources :items
      end
    end

    resources :users
    resources :contracts
  end

  get 'about/index'
  get 'note/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :city
  belongs_to :area
  belongs_to :user

  validates_presence_of :name, :address, :city, :area, :phone, :state
  validates :name,
    presence: false,
    length: { minimum: 2, maximum: 40 }
  validates :phone,
    presence: false,
    length: { minimum: 8, maximum: 16 }
  validates :address,
    presence: false,
    length: { minimum: 2, maximum: 255 }
  validates :note,
    presence: false,
    length: { minimum: 0, maximum: 2000 }

  enum state: [:pending, :confirmed, :shipping, :delivered, :refunded]
  enum delivery_way: [:atm, :personally, :line_pay, :cash]

  DEFAULT_VALUES = { state: :pending }


  def title
    "#{user.name} - #{created_at.strftime("%F")}"
  end

  def total_product
    order_items.reduce(0) { |result, item| result += item.quantity }
  end

  def total_price
    order_items.reduce(0) { |result, item| result += item.price }
  end

  def product_title
    order_items.first.product.product.title
  end

  def full_address
    "#{city.name}#{area.name}#{address}"
  end

  state_machine :initial => :pending do

    event :confirm do
      transition :pending => :confirmed
    end

    event :ship do
      transition :confirmed => :shipping
    end

    event :deliver do
      transition :shipping => :delivered
    end

    event :refund do
      transition :confirm => :refunded
    end

    event :complain_shipping do
      transition :shipping => :complained
    end

    event :complain_deliver do
      transition :delivered => :complained
    end
  end

end

app/controllers/admin/orders/items_controller.rb
class Admin::Orders::ItemsController < ResourcesController
  before_action :authenticate_admin!
  layout "admin"

  before_action only: [:new, :edit, :update, :create] do
    @order = ::Order.find params[:order_id]
  end

  def current_collection
    ::OrderItem.all.where(order_id: params[:order_id])
  end

  def permitted_attributes
    [ :product_id, :quantity, :order_id]
  end

  def url_after_create
    edit_admin_order_item_path(@order.id, current_collection.last.id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ResourcesController
  before_action :authenticate_admin!

  layout "admin"

  def current_collection
    ::Order.all
  end

  def permitted_attributes
    [
      :user, :state, :delivered_at, :shipped_at, :delivery_way,
      :name, :city, :area, :address, :phone, :note
    ]
  end

  def model_class_name
    'Order'
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :initialize_cart
  before_action :authenticate_user!
  before_action only: [:new, :create] do
    @delivery_way_options = Order.delivery_ways.map do |way, key|
      [Order.human_attribute_name("delivery_way.#{way}"), key]
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = current_user.orders.order(id: :desc)
  end

  def new
    @user = current_user
    @order = Order.new
    city_id = City.first.id
    @area_options = Area.where(city_id: city_id)
  end

  def create
    order = Order.new(order_params)
    order.user_id = current_user.id
    @cart.items.each do |item|
      order.order_items.new(
        product_id: item.product.id,
        quantity: item.quantity,
        price: item.price
      )
    end

    if order.save
      clear_cart
      flash[:notice] = "訂單送出成功！"
      redirect_to orders_path
    else
      @user = current_user
      @order = order
      @area_options = Area.where(city_id: order.city_id)
      flash[:alert] = order.errors.full_messages.join("\r\n")
      render 'orders/new'
    end

  end
  private
  def order_params
    params.require(:order).permit(:name, :phone,:city_id, :area_id, :address, :email, :note)
  end
end

app/helpers/admin/orders/items_helper.rb
module Admin::Orders::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= simple_form_for [:admin, current_object], html: { class: 'form-horizontal' } do |f| %>
  <%= hidden_field(:order, :id, value: current_object.id) %>
<%= render partial: 'shared/save', locals: { f: f, cancel_path: admin_orders_path } %>
<div class="form-body">
  <h4 class="block">訂單資訊</h4>
  <%= f.association :user, input_html: {class: 'form-control', class: 'input-large'} %>
  <%= f.input :total_price, disabled: true, input_html: { class: 'input-large'} %>
  <%= f.input :total_product, disabled: true, input_html: { class: 'input-large'} %>
  <%= f.input :state, collection: Order.human_attribute_enum('state'), include_blank: false, label_method: :last, value_method: :first, input_html: { class: 'input-small' } %>
  <div class="form-group">
    <%= f.label :shipped_at, class: 'control-label col-md-2' %>
    <div class="col-md-4">
      <div class="input-group date form_datetime bs-datetime" data-date-format="dd MM yyyy - HH:ii">
        <%= f.input_field :shipped_at, as: :string, class: 'form-control' %>
        <span class="input-group-addon">
          <button class="btn default date-reset" type="button">
            <i class="fa fa-times"></i>
          </button>
        </span>
        <span class="input-group-addon">
          <button class="btn default date-set" type="button">
            <i class="fa fa-calendar"></i>
          </button>
        </span>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :delivered_at, class: 'control-label col-md-2' %>
    <div class="col-md-4">
      <div class="input-group date form_datetime bs-datetime" data-date-format="dd MM yyyy - HH:ii">
        <%= f.input_field :delivered_at, as: :string, class: 'form-control' %>
        <span class="input-group-addon">
          <button class="btn default date-reset" type="button">
            <i class="fa fa-times"></i>
          </button>
        </span>
        <span class="input-group-addon">
          <button class="btn default date-set" type="button">
            <i class="fa fa-calendar"></i>
          </button>
        </span>
      </div>
    </div>
  </div>
  <h4 class="block">收件人資訊</h4>
  <%= f.input :name, input_html: { class: 'input-large'} %>
  <%= f.input :phone, input_html: { class: 'input-large'} %>
  <%= f.association :city, input_html: { class: 'input-large'} %>
  <%= f.association :area, input_html: { class: 'input-large'} %>
  <%= f.input :address, input_html: { class: 'input-large'} %>
<%= f.input :delivery_way, input_html: { class: 'input-large'},
  collection: Order.human_attribute_enum('delivery_way'), label_method: :last, value_method: :first, include_blank: false %>
  <%= f.input :note, input_html: { class: 'input-large'} %>


  <hr />
  <%= render partial: "items", locals: { order_id: current_object.id, items: current_object.order_items } unless current_object.new_record? %>
</div>

<%= render partial: 'shared/save', locals: { f: f, cancel_path: admin_orders_path } %>

<% end %>

<script type="text/javascript" charset="utf-8">
  $(".form_datetime").datetimepicker({
    autoclose: true,
    isRTL: App.isRTL(),
    format: "yyyy-mm-dd hh:ii",
    fontAwesome: true,
    pickerPosition: (App.isRTL() ? "bottom-right" : "bottom-left")
  });
</script>

app/views/admin/orders/_items.html.erb
<h4>
  訂購商品
</h4>
<hr />
<div class="btn-group">
    <%= link_to(new_admin_order_item_path(order_id), class: 'btn blue') do %>
    <i class="fa fa-plus"></i>
    <% end %>
</div>

<br />
<table class="table table-striped">
  <thead>
    <tr>
      <th> 名稱 </th>
      <th> 單價 </th>
      <th> 數量 </th>
      <th> 小記 </th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% items.each do |item| %>
    <tr>
      <td class="column-2"><%= item.product.full_title %></td>
      <td class="column-3"><%= item.product.price %></td>
      <td>
        <%= item.product.price %>
      </td>
      <td>
        <%= item.price %>
      </td>
      <td class="ui-helper-center">
        <%= link_to(edit_admin_order_item_path(order_id, item.id), class: 'btn btn-default btn-xs') do %>
        <i class="fa fa-pencil"></i>
        <% end %>
        <%= link_to(admin_order_item_path(order_id, item.id),  method: :delete, class: 'btn btn-default btn-xs', data: { "confirm-swal" =>  '確定刪除嗎 ?' }) do %>
        <i class="fa fa-trash"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/_table.html.erb
<div class="table-scrollable">
  <table class="table table-hover">
    <tr>
      <th>訂購人</th>
      <th>狀態</th>
      <th>商品數量</th>
      <th>總計</th>
      <th>成立時間</th>
      <th style="text-align:center">操作</th>
    </tr>
    <% current_collection.each do |order| %>
    <tr>
      <td>
        <%= order.user.name %>
      </td>
      <td>
        <%= t order.state %>
      </td>
      <td>
        <%= order.total_product %>
      </td>
      <td>
        <%= order.total_price %>
      </td>
      <td>
        <%= order.created_at.strftime("%Y-%m-%d %H:%M") %>
      </td>
      <td class="ui-helper-center">
        <%= link_to(edit_admin_order_path(order), class: 'btn btn-default btn-xs') do %>
        <i class="fa fa-pencil"></i>
        <% end %>
        <%= link_to(admin_order_path(order),  method: :delete, class: 'btn btn-default btn-xs', data: { "confirm-swal" =>  '確定刪除嗎 ?' }) do %>
        <i class="fa fa-trash"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/orders/_toolbar.html.erb
<div class="fixed-table-toolbar">
  <div class="btn-group pull-left">
    <%= link_to(new_admin_order_path, class: 'btn blue' ) do %>
    <i class="fa fa-plus"></i>
    <% end %>
  </div>
  <div class="pull-right search">
    <button id="search-btn" class="btn btn-default" type="buttton" name="search" title="search"><i class="fa fa-search"></i></button>
  </div>
  <div class="pull-right search">
    <input id="keyword" class="form-control input-inline" type="text" value="<%= params[:title] %>" placeholder="過濾訂單">
  </div>
</div>

app/views/admin/orders/edit.html.erb
<div class="page-bar">
  <%= breadcrumb(link_to('訂單', admin_orders_path), '編輯訂單') %>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">
        編輯訂單
      </h2>
      <div class="portlet box blue">
        <div class="portlet-title">
          <div class="caption">
            <%= current_object.title %>
          </div>
        </div>
        <div class="portlet-body form">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="page-bar">
  <%= breadcrumb('訂單') %>
</div>
<h1 class="page-title">訂單</h1>

<%= render partial: 'toolbar' %>
<%= render partial: 'table' %>

app/views/admin/orders/new.html.erb
<div class="page-bar">
  <%= breadcrumb(link_to('商品', admin_orders_path), '新增訂單') %>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h2 class="page-header">
        新增訂單
      </h2>
      <div class="portlet box blue">
        <div class="portlet-title">
          <div class="caption">
            Append
          </div>
        </div>
        <div class="portlet-body form">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>