config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    sessions: "admin/sessions"
  }
  devise_for(
    :users,
    controllers: {
      sessions: "user/sessions",
      passwords: "user/passwords",
      registrations: "user/registrations",
      omniauth_callbacks: "user/omniauth_callbacks"
    }
  )
  get 'products/show'

  get 'index/index'
  resource :cart, only:[:show, :destroy] do
    member do
      post :add, path: 'add/:id/(:quantity)'
      post :update_quantity, path: 'update/:id'
      delete :remove, path: 'remove/:id'
      get "checkout"
    end
  end
  resources :orders, only:[:index, :new, :create, :show]

  resources :cities, only:[] do
    scope module: :cities do
      member do
        resources :areas, only:[:index]
      end
    end
  end

  root "index#index"

  resources :products
  resources :articles
  resources :contracts, only:[:new, :create]


  namespace :admin do
    root 'products#index'
    devise_scope :admin do
      authenticated :admin do
        root 'products#index', as: :authenticated_root
      end
    end
    resources :products do
        scope module: :products do
          resources :images, only: [:index, :create, :destroy]
          resources :specs do
            member do
              get :switch_seq, path: 'switch/:target_id'
            end
          end
        end
    end
    resources :orders do
      scope module: :orders do
        resources :items
      end
    end

    resources :users
    resources :contracts
  end

  get 'about/index'
  get 'note/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_admin_menu.html.erb
<div class="top-menu">
  <ul class="nav navbar-nav pull-right">
    <li class="dropdown dropdown-user">
      <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <img alt="" class="img-circle" src="https://ih0.redbubble.net/image.363620920.6389/st%2Csmall%2C215x235-pad%2C210x230%2Cf8f8f8.lite-1u2.jpg" style="width:20px; height:20px">
        <span class="username username-hide-on-mobile"> <%= current_admin.try(:email) %> </span>
        <i class="fa fa-angle-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-menu-default">
        <li>
          <%= link_to('登出', destroy_admin_session_path, method: :delete) %>
        </li>
      </ul>
    </li>
  </ul>
</div>
<div class="hor-menu hidden-sm hidden-xs">
  <ul class="nav navbar-nav">
    <li class="classic-menu-dropdown  aria-haspopup="true">
      <%= link_to("商品", admin_products_path) %>
    </li>
    <li class="classic-menu-dropdown" aria-haspopup="true">
      <%= link_to("訂單", admin_orders_path) %>
    </li>
    <li class="classic-menu-dropdown" aria-haspopup="true">
      <%= link_to("會員", admin_users_path) %>
    </li>
    <li class="classic-menu-dropdown" aria-haspopup="true">
      <%= link_to("首頁", "javascript:void(0);") %>
    </li>
    <li class="classic-menu-dropdown" aria-haspopup="true">
      <%= link_to("訊息", admin_contracts_path) %>
    </li>
  </ul>
</div>

app/views/shared/_flash.html.erb
<script type="text/javascript" charset="utf-8">

  <% unless flash[:alert].nil? %>
  swal('Error', "<%= j flash[:alert] %>", "error");
  <% flash.discard(:alert) %>
  <% end %>

  <% unless flash[:notice].nil? %>
  swal('Notice', "<%= j flash[:notice] %>", "info");
  <% flash.discard(:notice) %>
  <% end %>

  <% unless flash[:success].nil? %>
  swal('Success', "<%= j flash[:success] %>", "success");
  <% flash.discard(:Success) %>
  <% end %>


</script>

app/views/shared/_menu.html.erb
<!-- Menu -->
<div class="wrap_menu">
  <nav class="menu">
    <ul class="main_menu">
      <li <%= 'class=sale-noti' if request.env['PATH_INFO'] == root_path %> >
        <%= link_to("首頁", root_path) %>
      </li>
      <% Product.publish.each do |product| %>
      <li <%= 'class=sale-noti' if request.env['PATH_INFO'] == product_path(product.id) %> >
        <%= link_to(product.name, product_path(product.id)) %>
      </li>
      <% end %>

      <li <%= 'class=sale-noti' if request.env['PATH_INFO'] == about_index_path %> >
        <%= link_to("關於李媽媽青果社", about_index_path) %>
      </li>
      <li <%= 'class=sale-noti' if request.env['PATH_INFO'] == note_index_path %> >
        <%= link_to("訂購流程", note_index_path) %>
      </li>
      <li <%= 'class=sale-noti' if request.env['PATH_INFO'] == articles_path %> >
        <%= link_to("部落格", 'http://leefruit640.blogspot.tw/', target: "_blank") %>
      </li>
      <li <%= 'class=sale-noti' if request.env['PATH_INFO'] == new_contract_path %> >
        <%= link_to("聯絡我們", new_contract_path) %>
      </li>
    </ul>
  </nav>
</div>

app/views/shared/_mobile_menu.html.erb
<li class="item-menu-mobile">
<%= link_to("首頁", root_path) %>
</li>
<li class="item-menu-mobile">
<%= link_to("帝王柑", product_path(1)) %>
</li>
<li class="item-menu-mobile">
<%= link_to("關於李媽媽青果社", about_index_path) %>
</li>
<li class="item-menu-mobile">
<%= link_to("訂購流程", note_index_path) %>
</li>
<li class="item-menu-mobile">
<%= link_to("部落格", articles_path) %>
</li>
<li class="item-menu-mobile">
<%= link_to("聯絡我們", new_contract_path) %>
</li>

app/views/shared/_save.html.erb
<div class="form-actions">
  <%= f.button :submit, '儲存', class: 'btn green' %>
  <%= link_to("取消", cancel_path, class: "btn default") %>
</div>

app/views/shared/_toastr.html.erb
<script type="text/javascript" charset="utf-8">

  $(document).on('ready page:load', function() {

    <% unless flash[:alert].nil? %>
      toastr.error('<%= j flash[:alert] %>', 'Error');
      <% flash.discard(:alert) %>
    <% end %>

    <% unless flash[:notice].nil? %>
      toastr.info('<%= j flash[:notice] %>', 'Info');
      <% flash.discard(:notice) %>
    <% end %>

    <% unless flash[:success].nil? %>
      toastr.success('<%= j flash[:success] %>', 'Success');
      <% flash.discard(:Success) %>
    <% end %>

  });

</script>