config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    sessions: "admin/sessions"
  }
  devise_for(
    :users,
    controllers: {
      sessions: "user/sessions",
      passwords: "user/passwords",
      registrations: "user/registrations",
      omniauth_callbacks: "user/omniauth_callbacks"
    }
  )
  get 'products/show'

  get 'index/index'
  resource :cart, only:[:show, :destroy] do
    member do
      post :add, path: 'add/:id/(:quantity)'
      post :update_quantity, path: 'update/:id'
      delete :remove, path: 'remove/:id'
      get "checkout"
    end
  end
  resources :orders, only:[:index, :new, :create, :show]

  resources :cities, only:[] do
    scope module: :cities do
      member do
        resources :areas, only:[:index]
      end
    end
  end

  root "index#index"

  resources :products
  resources :articles
  resources :contracts, only:[:new, :create]


  namespace :admin do
    root 'products#index'
    devise_scope :admin do
      authenticated :admin do
        root 'products#index', as: :authenticated_root
      end
    end
    resources :products do
        scope module: :products do
          resources :images, only: [:index, :create, :destroy]
          resources :specs do
            member do
              get :switch_seq, path: 'switch/:target_id'
            end
          end
        end
    end
    resources :orders do
      scope module: :orders do
        resources :items
      end
    end

    resources :users
    resources :contracts
  end

  get 'about/index'
  get 'note/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  has_many :specs
  scope :publish, -> { where(is_finish: true).where(is_public: true) }

  validates_presence_of :name, :price, :description, :description_2

  before_update do
    self.is_finish ||= true
  end

end

app/models/product/image.rb
class Product::Image < ApplicationRecord
  belongs_to :product
  mount_uploader :file, ProductImageUploader
end

app/models/product/spec.rb
class Product::Spec < ApplicationRecord
  belongs_to :product

  validates_presence_of :title, :price

  mount_uploader :image, ProductSpecImageUploader

  before_create do
    self.seq = self.class.where(product_id: self.product_id).size + 1
  end

  def full_title
    "#{product.title} - #{title}"
  end

end

app/controllers/admin/products/images_controller.rb
class Admin::Products::ImagesController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token, :only => [:index, :create, :destroy]

  def index
    images = ::Product.find(params[:product_id]).images
    images = images.map do |image|
      {
        id: image.id,
        file_url: image.file.url ,
        file_name: image.file.file.filename
      }
    end

    render json: images.to_json, status: :ok

  end

  def create
    image = Product::Image.new(
      product: Product.find(params[:product_id]),
      file: params[:file]
    )

    if image.save

      response_image = {}
      response_image[:id] = image.id
      response_image[:file_url] = image.file.url
      response_image[:file_name] = image.file.file.filename

      render json: {
        image: response_image.to_json,
        filelink: image.file.url
      }, status: :ok
    else
      render json: { errors: service.errors.full_messages.last }, status: :unprocessable_entity
    end
  end

  def destroy
    product = Product.find params[:product_id]
    product.images.delete(Product::Image.find(params[:id]))
    render json: {}, status: :ok
  end
end

app/controllers/admin/products/specs_controller.rb
class Admin::Products::SpecsController < ResourcesController

  before_action :authenticate_admin!
  layout "admin"

  before_action only: [:new, :edit, :update, :create] do
    @product = ::Product.find params[:product_id]
  end

  def current_collection
    ::Product::Spec.all.order(:product_id, :seq)
  end

  def permitted_attributes
    [
      :title, :price, :product_id, :image, :seq
    ]
  end

  def switch_seq
    specs  = ::Product.find(params[:product_id]).specs
    source = specs.find(params[:id])
    target = specs.find(params[:target_id])

    source.seq = target.seq
    target.seq = source.seq_was
    source.save! and target.save!

    redirect_to edit_admin_product_path(params[:product_id])
  end

  def action_after_create
    edit_admin_product_spec_path(@product.id, current_collection.last.id)
  end

  def param_key
    "product_spec"
  end

  def model_class_name
    "Product::Spec"
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ResourcesController

  before_action :authenticate_admin!

  layout "admin"

  def new
    Product.new.save(validate: false)
    redirect_to edit_admin_product_path(Product.last.id)
  end

  def current_collection
    ::Product.where(is_finish: true)
  end

  def permitted_attributes
    [
      :name, :price, :description,
      :description_2, :is_public,
    ]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find params[:id]
  end
end

app/helpers/admin/product/images_helper.rb
module Admin::Product::ImagesHelper
end

app/helpers/admin/products/specs_helper.rb
module Admin::Products::SpecsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, current_object], html: { class: 'form-horizontal' } do |f| %>
  <%= hidden_field(:product, :id, value: current_object.id) %>
<%= render partial: 'shared/save', locals: { f: f, cancel_path: admin_products_path } %>
<div class="form-body">
  <%= f.input :name, input_html: {class: 'form-control', class: 'input-large'} %>
  <%= f.input :price, input_html: {class: 'form-control', class: 'input-large'} %>
  <%= f.input :is_public, as: :boolean %>
  <%= f.input :description, input_html: {class: 'form-control input-xlarge', rows: '12'} %>
  <%= f.input :description_2, as: :text,input_html: {class: 'form-control input-xlarge', rows: '12'} %>
  <div class="form-group m-form__group row">
    <label class="col-md-2 control-label">
      圖片
    </label>
    <div class="col-md-6">
      <div class="col-sm-6 col-md-3" v-for="(image, index) in images">
        <img :src="image.file_url " height="106" width="120">
        <div style="margin:2px;  padding-right:0px; text-align: center;">
          <a type="button" target="_blank" :href="image.file_url" class="btn m-btn--pill btn-danger" data-placement="left">
            <i class="fa fa-eye"></i>
          </a>
          <button type="button" class="btn m-btn--pill btn-danger" data-placement="left" data-title="Do you agree to the Terms and Conditions?"  v-on:click="removeImages(image.id)">
             <i class="fa fa-trash"></i>
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group m-form__group row">
    <label class="col-md-2 control-label">
    </label>
    <div class="col-md-6">
      <div class="m-dropzone dropzone m-dropzone--primary" id="dropzone">
        <div class="m-dropzone__msg dz-message needsclick">
          <h3 class="m-dropzone__msg-title">
            拖曳或點擊後上傳
          </h3>
          <span class="m-dropzone__msg-desc">
            最多可上傳10個檔案
          </span>
        </div>
      </div>
    </div>
  </div>

  <hr />
  <%= render partial: "specs", locals: { product_id: current_object.id, specs: current_object.specs.order(:seq) } %>

</div>

<%= render partial: 'shared/save', locals: { f: f, cancel_path: admin_products_path } %>
<% end %>

app/views/admin/products/_save.html.erb
<div class="form-actions">
  <%= f.button :submit, '儲存', class: 'btn green' %>
  <%= link_to("取消", cancel_path, class: "btn default") %>
</div>

app/views/admin/products/_specs.html.erb
<h4>
  商品規格
</h4>
<hr />
<div class="btn-group">
    <%= link_to(new_admin_product_spec_path(product_id), class: 'btn blue') do %>
    <i class="fa fa-plus"></i>
    <% end %>
</div>

<br />
<table class="table table-striped">
  <thead>
    <tr>
      <th width="7%"> 順序 </th>
      <th> 名稱 </th>
      <th> 價格 </th>
      <th> 圖片 </th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% specs.each_with_index do |spec, index| %>
    <tr>
      <td>
        <% if spec != specs.first %>
        <%= link_to(switch_seq_admin_product_spec_path(spec.product_id, spec.id, specs[index-1][:id]), class: '') do %>
        <i class="fa fa-angle-up"></i>
        <% end %>
        <% end %>
        <% if spec != specs.last %>
        <%= link_to(switch_seq_admin_product_spec_path(spec.product_id, spec.id, specs[index+1][:id]), class: '') do %>
          <i class="fa fa-angle-down"></i>
          <% end %>
        <% end %>
      </td>
      <td>
        <%= spec.title %>
      </td>
      <td>
        <%= spec.price %>
      </td>
      <td>
        <img src="<%= spec.image.url %>" width="60" height="60">
      </td>
      <td class="ui-helper-center">
        <%= link_to(edit_admin_product_spec_path(product_id, spec.id), class: 'btn btn-default btn-xs') do %>
        <i class="fa fa-pencil"></i>
        <% end %>
        <%= link_to(admin_product_spec_path(product_id, spec.id),  method: :delete, class: 'btn btn-default btn-xs', data: { "confirm-swal" =>  '確定刪除嗎 ?' }) do %>
        <i class="fa fa-trash"></i>
        <% end %>
      </td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/admin/products/_table.html.erb
<div class="table-scrollable">
  <table class="table table-hover">
    <tr>
      <th>商品</th>
      <th>價格</th>
      <th>建立時間</th>
      <th>修改時間</th>
      <th style="text-align:center">操作</th>
    </tr>
    <% current_collection.each do |product| %>
    <tr>
      <td>
        <%= product.name %>
      </td>
      <td>
        <%= product.price %>
      </td>
      <td>
        <%= product.created_at.strftime("%Y-%m-%d %H:%M") %>
      </td>
      <td>
        <%= product.updated_at.strftime("%Y-%m-%d %H:%M") %>
      </td>
      <td class="ui-helper-center">
        <%= link_to(edit_admin_product_path(product), class: 'btn btn-default btn-xs') do %>
        <i class="fa fa-pencil"></i>
        <% end %>
        <%= link_to(admin_product_path(product),  method: :delete, class: 'btn btn-default btn-xs', data: { "confirm-swal" =>  '確定刪除嗎 ?' }) do %>
        <i class="fa fa-trash"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/products/_toolbar.html.erb
<div class="fixed-table-toolbar">
  <div class="btn-group pull-left">
    <%= link_to(new_admin_product_path, class: 'btn blue' ) do %>
    <i class="fa fa-plus"></i>
    <% end %>
  </div>
  <div class="pull-right search">
    <button id="search-btn" class="btn btn-default" type="buttton" name="search" title="search"><i class="fa fa-search"></i></button>
  </div>
  <div class="pull-right search">
    <input id="keyword" class="form-control input-inline" type="text" value="<%= params[:title] %>" placeholder="過濾產品名稱">
  </div>
</div>

app/views/admin/products/edit.html.erb
<div class="page-bar">
  <%= breadcrumb(link_to('商品', admin_products_path), current_object.title) %>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">
        修改商品
      </h2>
      <div class="portlet box blue">
        <div class="portlet-title">
          <div class="caption">
            <%= current_object.title %>
          </div>
        </div>
        <div class="portlet-body form">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="page-bar">
  <%= breadcrumb('商品') %>
</div>
<h1 class="page-title">商品</h1>

<%= render partial: 'toolbar' %>
<%= render partial: 'table' %>